
F3M/FunctionMerging.cpp:
	mkdir -p $(@D)
	curl -o $@ https://raw.githubusercontent.com/ppetoumenos/llvm-project/LSHfm/llvm/lib/Transforms/IPO/FunctionMerging.cpp
HyFM/FunctionMerging.cpp:
	mkdir -p $(@D)
	curl -o $@ https://raw.githubusercontent.com/rcorcs/llvm-project/newfm/llvm/lib/Transforms/IPO/FunctionMerging.cpp
SalSSA/FunctionMerging.cpp:
	mkdir -p $(@D)
	curl -o $@ https://raw.githubusercontent.com/rcorcs/llvm-project/func-merge/llvm/lib/Transforms/IPO/FunctionMerging.cpp
