; AUTOMATICALLY GENERATED BY tools/llvm-nextfm-remark/compare-mergesize.rb
;
; RUN: %opt -S --passes="multiple-func-merging" --multiple-func-merging-only=get_sof --multiple-func-merging-only=get_sos -o %t.mfm.ll %s
; RUN: %opt -S --passes="func-merging" --func-merging-only=get_sof --func-merging-only=get_sos -o %t.fm.ll %s
; RUN: %llc --filetype=obj %t.mfm.ll -o %t.mfm.o
; RUN: %llc --filetype=obj %t.fm.ll -o %t.fm.o
; RUN: %strip %t.mfm.o
; RUN: %strip %t.fm.o
; RUN: [[ $(stat -c%%s %t.mfm.o) -le $(stat -c%%s %t.fm.o) ]]
; XFAIL: *

; ModuleID = '../benchmarks/mibench/consumer/jpeg/cjpeg.bc'
source_filename = "llvm-link"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.jpeg_decompress_struct.541 = type { %struct.jpeg_error_mgr*, %struct.jpeg_memory_mgr*, %struct.jpeg_progress_mgr*, i32, i32, %struct.jpeg_source_mgr.526*, i32, i32, i32, i32, i32, i32, i32, double, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i8**, i32, i32, i32, i32, i32, [64 x i32]*, [4 x %struct.JQUANT_TBL*], [4 x %struct.JHUFF_TBL*], [4 x %struct.JHUFF_TBL*], i32, %struct.jpeg_component_info*, i32, i32, [16 x i8], [16 x i8], [16 x i8], i32, i32, i8, i16, i16, i32, i8, i32, i32, i32, i32, i32, i8*, i32, [4 x %struct.jpeg_component_info*], i32, i32, i32, [10 x i32], i32, i32, i32, i32, i32, %struct.jpeg_decomp_master.530*, %struct.jpeg_d_main_controller.531*, %struct.jpeg_d_coef_controller.532*, %struct.jpeg_d_post_controller.533*, %struct.jpeg_input_controller.534*, %struct.jpeg_marker_reader.535*, %struct.jpeg_entropy_decoder.536*, %struct.jpeg_inverse_dct.537*, %struct.jpeg_upsampler.538*, %struct.jpeg_color_deconverter.539*, %struct.jpeg_color_quantizer.540* }
%struct.jpeg_error_mgr = type { void (%struct.jpeg_common_struct*)*, void (%struct.jpeg_common_struct*, i32)*, void (%struct.jpeg_common_struct*)*, void (%struct.jpeg_common_struct*, i8*)*, void (%struct.jpeg_common_struct*)*, i32, %union.anon, i32, i64, i8**, i32, i8**, i32, i32 }
%struct.jpeg_common_struct = type { %struct.jpeg_error_mgr*, %struct.jpeg_memory_mgr*, %struct.jpeg_progress_mgr*, i32, i32 }
%union.anon = type { [8 x i32], [48 x i8] }
%struct.jpeg_memory_mgr = type { i8* (%struct.jpeg_common_struct*, i32, i64)*, i8* (%struct.jpeg_common_struct*, i32, i64)*, i8** (%struct.jpeg_common_struct*, i32, i32, i32)*, [64 x i16]** (%struct.jpeg_common_struct*, i32, i32, i32)*, %struct.jvirt_sarray_control* (%struct.jpeg_common_struct*, i32, i32, i32, i32, i32)*, %struct.jvirt_barray_control* (%struct.jpeg_common_struct*, i32, i32, i32, i32, i32)*, {}*, i8** (%struct.jpeg_common_struct*, %struct.jvirt_sarray_control*, i32, i32, i32)*, [64 x i16]** (%struct.jpeg_common_struct*, %struct.jvirt_barray_control*, i32, i32, i32)*, void (%struct.jpeg_common_struct*, i32)*, {}*, i64 }
%struct.jvirt_sarray_control = type { i8**, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, %struct.jvirt_sarray_control*, %struct.backing_store_struct }
%struct.backing_store_struct = type { void (%struct.jpeg_common_struct.775*, %struct.backing_store_struct*, i8*, i64, i64)*, void (%struct.jpeg_common_struct.775*, %struct.backing_store_struct*, i8*, i64, i64)*, void (%struct.jpeg_common_struct.775*, %struct.backing_store_struct*)*, %struct._IO_FILE*, [64 x i8] }
%struct.jpeg_common_struct.775 = type { %struct.jpeg_error_mgr.766*, %struct.jpeg_memory_mgr.773*, %struct.jpeg_progress_mgr*, i32, i32 }
%struct.jpeg_error_mgr.766 = type { {}*, void (%struct.jpeg_common_struct.775*, i32)*, {}*, void (%struct.jpeg_common_struct.775*, i8*)*, {}*, i32, %union.anon, i32, i64, i8**, i32, i8**, i32, i32 }
%struct.jpeg_memory_mgr.773 = type { i8* (%struct.jpeg_common_struct.775*, i32, i64)*, i8* (%struct.jpeg_common_struct.775*, i32, i64)*, i8** (%struct.jpeg_common_struct.775*, i32, i32, i32)*, [64 x i16]** (%struct.jpeg_common_struct.775*, i32, i32, i32)*, %struct.jvirt_sarray_control* (%struct.jpeg_common_struct.775*, i32, i32, i32, i32, i32)*, %struct.jvirt_barray_control* (%struct.jpeg_common_struct.775*, i32, i32, i32, i32, i32)*, {}*, i8** (%struct.jpeg_common_struct.775*, %struct.jvirt_sarray_control*, i32, i32, i32)*, [64 x i16]** (%struct.jpeg_common_struct.775*, %struct.jvirt_barray_control*, i32, i32, i32)*, void (%struct.jpeg_common_struct.775*, i32)*, {}*, i64 }
%struct.jvirt_barray_control = type { [64 x i16]**, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, %struct.jvirt_barray_control*, %struct.backing_store_struct }
%struct._IO_FILE = type { i32, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, %struct._IO_marker*, %struct._IO_FILE*, i32, i32, i64, i16, i8, [1 x i8], i8*, i64, %struct._IO_codecvt*, %struct._IO_wide_data*, %struct._IO_FILE*, i8*, i64, i32, [20 x i8] }
%struct._IO_marker = type opaque
%struct._IO_codecvt = type opaque
%struct._IO_wide_data = type opaque
%struct.jpeg_progress_mgr = type { {}*, i64, i64, i32, i32 }
%struct.jpeg_source_mgr.526 = type { i8*, i64, void (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)*, void (%struct.jpeg_decompress_struct.541*, i64)*, {}*, void (%struct.jpeg_decompress_struct.541*)* }
%struct.JQUANT_TBL = type { [64 x i16], i32 }
%struct.JHUFF_TBL = type { [17 x i8], [256 x i8], i32 }
%struct.jpeg_component_info = type { i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, %struct.JQUANT_TBL*, i8* }
%struct.jpeg_decomp_master.530 = type { void (%struct.jpeg_decompress_struct.541*)*, void (%struct.jpeg_decompress_struct.541*)*, i32 }
%struct.jpeg_d_main_controller.531 = type { void (%struct.jpeg_decompress_struct.541*, i32)*, void (%struct.jpeg_decompress_struct.541*, i8**, i32*, i32)* }
%struct.jpeg_d_coef_controller.532 = type { void (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)*, void (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*, i8***)*, %struct.jvirt_barray_control** }
%struct.jpeg_d_post_controller.533 = type { void (%struct.jpeg_decompress_struct.541*, i32)*, void (%struct.jpeg_decompress_struct.541*, i8***, i32*, i32, i8**, i32*, i32)* }
%struct.jpeg_input_controller.534 = type { i32 (%struct.jpeg_decompress_struct.541*)*, void (%struct.jpeg_decompress_struct.541*)*, void (%struct.jpeg_decompress_struct.541*)*, void (%struct.jpeg_decompress_struct.541*)*, i32, i32 }
%struct.jpeg_marker_reader.535 = type { void (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)*, [16 x i32 (%struct.jpeg_decompress_struct.541*)*], i32, i32, i32, i32 }
%struct.jpeg_entropy_decoder.536 = type { void (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*, [64 x i16]**)* }
%struct.jpeg_inverse_dct.537 = type { void (%struct.jpeg_decompress_struct.541*)*, [10 x void (%struct.jpeg_decompress_struct.541*, %struct.jpeg_component_info*, i16*, i8**, i32)*] }
%struct.jpeg_upsampler.538 = type { void (%struct.jpeg_decompress_struct.541*)*, void (%struct.jpeg_decompress_struct.541*, i8***, i32*, i32, i8**, i32*, i32)*, i32 }
%struct.jpeg_color_deconverter.539 = type { void (%struct.jpeg_decompress_struct.541*)*, void (%struct.jpeg_decompress_struct.541*, i8***, i32, i8**, i32)* }
%struct.jpeg_color_quantizer.540 = type { void (%struct.jpeg_decompress_struct.541*, i32)*, void (%struct.jpeg_decompress_struct.541*, i8**, i8**, i32)*, void (%struct.jpeg_decompress_struct.541*)*, void (%struct.jpeg_decompress_struct.541*)* }

; Function Attrs: noinline nounwind optnone ssp uwtable
define hidden i32 @get_sof(%struct.jpeg_decompress_struct.541* %0, i32 %1, i32 %2) #0 {
  %4 = alloca i32, align 4
  %5 = alloca %struct.jpeg_decompress_struct.541*, align 8
  %6 = alloca i32, align 4
  %7 = alloca i32, align 4
  %8 = alloca i64, align 8
  %9 = alloca i32, align 4
  %10 = alloca i32, align 4
  %11 = alloca %struct.jpeg_component_info*, align 8
  %12 = alloca %struct.jpeg_source_mgr.526*, align 8
  %13 = alloca i8*, align 8
  %14 = alloca i64, align 8
  %15 = alloca i32*, align 8
  %16 = alloca i32*, align 8
  store %struct.jpeg_decompress_struct.541* %0, %struct.jpeg_decompress_struct.541** %5, align 8
  store i32 %1, i32* %6, align 4
  store i32 %2, i32* %7, align 4
  %17 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %18 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %17, i32 0, i32 5
  %19 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %18, align 8
  store %struct.jpeg_source_mgr.526* %19, %struct.jpeg_source_mgr.526** %12, align 8
  %20 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %21 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %20, i32 0, i32 0
  %22 = load i8*, i8** %21, align 8
  store i8* %22, i8** %13, align 8
  %23 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %24 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %23, i32 0, i32 1
  %25 = load i64, i64* %24, align 8
  store i64 %25, i64* %14, align 8
  %26 = load i32, i32* %6, align 4
  %27 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %28 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %27, i32 0, i32 44
  store i32 %26, i32* %28, align 8
  %29 = load i32, i32* %7, align 4
  %30 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %31 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %30, i32 0, i32 45
  store i32 %29, i32* %31, align 4
  br label %32

32:                                               ; preds = %3
  %33 = load i64, i64* %14, align 8
  %34 = icmp eq i64 %33, 0
  br i1 %34, label %35, label %50

35:                                               ; preds = %32
  %36 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %37 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %36, i32 0, i32 3
  %38 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %37, align 8
  %39 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %40 = call i32 %38(%struct.jpeg_decompress_struct.541* %39)
  %41 = icmp ne i32 %40, 0
  br i1 %41, label %43, label %42

42:                                               ; preds = %35
  store i32 0, i32* %4, align 4
  br label %544

43:                                               ; preds = %35
  %44 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %45 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %44, i32 0, i32 0
  %46 = load i8*, i8** %45, align 8
  store i8* %46, i8** %13, align 8
  %47 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %48 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %47, i32 0, i32 1
  %49 = load i64, i64* %48, align 8
  store i64 %49, i64* %14, align 8
  br label %50

50:                                               ; preds = %43, %32
  %51 = load i64, i64* %14, align 8
  %52 = add i64 %51, -1
  store i64 %52, i64* %14, align 8
  %53 = load i8*, i8** %13, align 8
  %54 = getelementptr inbounds i8, i8* %53, i32 1
  store i8* %54, i8** %13, align 8
  %55 = load i8, i8* %53, align 1
  %56 = zext i8 %55 to i32
  %57 = shl i32 %56, 8
  %58 = zext i32 %57 to i64
  store i64 %58, i64* %8, align 8
  %59 = load i64, i64* %14, align 8
  %60 = icmp eq i64 %59, 0
  br i1 %60, label %61, label %76

61:                                               ; preds = %50
  %62 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %63 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %62, i32 0, i32 3
  %64 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %63, align 8
  %65 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %66 = call i32 %64(%struct.jpeg_decompress_struct.541* %65)
  %67 = icmp ne i32 %66, 0
  br i1 %67, label %69, label %68

68:                                               ; preds = %61
  store i32 0, i32* %4, align 4
  br label %544

69:                                               ; preds = %61
  %70 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %71 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %70, i32 0, i32 0
  %72 = load i8*, i8** %71, align 8
  store i8* %72, i8** %13, align 8
  %73 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %74 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %73, i32 0, i32 1
  %75 = load i64, i64* %74, align 8
  store i64 %75, i64* %14, align 8
  br label %76

76:                                               ; preds = %69, %50
  %77 = load i64, i64* %14, align 8
  %78 = add i64 %77, -1
  store i64 %78, i64* %14, align 8
  %79 = load i8*, i8** %13, align 8
  %80 = getelementptr inbounds i8, i8* %79, i32 1
  store i8* %80, i8** %13, align 8
  %81 = load i8, i8* %79, align 1
  %82 = zext i8 %81 to i64
  %83 = load i64, i64* %8, align 8
  %84 = add nsw i64 %83, %82
  store i64 %84, i64* %8, align 8
  br label %85

85:                                               ; preds = %76
  br label %86

86:                                               ; preds = %85
  %87 = load i64, i64* %14, align 8
  %88 = icmp eq i64 %87, 0
  br i1 %88, label %89, label %104

89:                                               ; preds = %86
  %90 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %91 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %90, i32 0, i32 3
  %92 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %91, align 8
  %93 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %94 = call i32 %92(%struct.jpeg_decompress_struct.541* %93)
  %95 = icmp ne i32 %94, 0
  br i1 %95, label %97, label %96

96:                                               ; preds = %89
  store i32 0, i32* %4, align 4
  br label %544

97:                                               ; preds = %89
  %98 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %99 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %98, i32 0, i32 0
  %100 = load i8*, i8** %99, align 8
  store i8* %100, i8** %13, align 8
  %101 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %102 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %101, i32 0, i32 1
  %103 = load i64, i64* %102, align 8
  store i64 %103, i64* %14, align 8
  br label %104

104:                                              ; preds = %97, %86
  %105 = load i64, i64* %14, align 8
  %106 = add i64 %105, -1
  store i64 %106, i64* %14, align 8
  %107 = load i8*, i8** %13, align 8
  %108 = getelementptr inbounds i8, i8* %107, i32 1
  store i8* %108, i8** %13, align 8
  %109 = load i8, i8* %107, align 1
  %110 = zext i8 %109 to i32
  %111 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %112 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %111, i32 0, i32 42
  store i32 %110, i32* %112, align 8
  br label %113

113:                                              ; preds = %104
  br label %114

114:                                              ; preds = %113
  %115 = load i64, i64* %14, align 8
  %116 = icmp eq i64 %115, 0
  br i1 %116, label %117, label %132

117:                                              ; preds = %114
  %118 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %119 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %118, i32 0, i32 3
  %120 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %119, align 8
  %121 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %122 = call i32 %120(%struct.jpeg_decompress_struct.541* %121)
  %123 = icmp ne i32 %122, 0
  br i1 %123, label %125, label %124

124:                                              ; preds = %117
  store i32 0, i32* %4, align 4
  br label %544

125:                                              ; preds = %117
  %126 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %127 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %126, i32 0, i32 0
  %128 = load i8*, i8** %127, align 8
  store i8* %128, i8** %13, align 8
  %129 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %130 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %129, i32 0, i32 1
  %131 = load i64, i64* %130, align 8
  store i64 %131, i64* %14, align 8
  br label %132

132:                                              ; preds = %125, %114
  %133 = load i64, i64* %14, align 8
  %134 = add i64 %133, -1
  store i64 %134, i64* %14, align 8
  %135 = load i8*, i8** %13, align 8
  %136 = getelementptr inbounds i8, i8* %135, i32 1
  store i8* %136, i8** %13, align 8
  %137 = load i8, i8* %135, align 1
  %138 = zext i8 %137 to i32
  %139 = shl i32 %138, 8
  %140 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %141 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %140, i32 0, i32 7
  store i32 %139, i32* %141, align 4
  %142 = load i64, i64* %14, align 8
  %143 = icmp eq i64 %142, 0
  br i1 %143, label %144, label %159

144:                                              ; preds = %132
  %145 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %146 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %145, i32 0, i32 3
  %147 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %146, align 8
  %148 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %149 = call i32 %147(%struct.jpeg_decompress_struct.541* %148)
  %150 = icmp ne i32 %149, 0
  br i1 %150, label %152, label %151

151:                                              ; preds = %144
  store i32 0, i32* %4, align 4
  br label %544

152:                                              ; preds = %144
  %153 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %154 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %153, i32 0, i32 0
  %155 = load i8*, i8** %154, align 8
  store i8* %155, i8** %13, align 8
  %156 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %157 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %156, i32 0, i32 1
  %158 = load i64, i64* %157, align 8
  store i64 %158, i64* %14, align 8
  br label %159

159:                                              ; preds = %152, %132
  %160 = load i64, i64* %14, align 8
  %161 = add i64 %160, -1
  store i64 %161, i64* %14, align 8
  %162 = load i8*, i8** %13, align 8
  %163 = getelementptr inbounds i8, i8* %162, i32 1
  store i8* %163, i8** %13, align 8
  %164 = load i8, i8* %162, align 1
  %165 = zext i8 %164 to i32
  %166 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %167 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %166, i32 0, i32 7
  %168 = load i32, i32* %167, align 4
  %169 = add i32 %168, %165
  store i32 %169, i32* %167, align 4
  br label %170

170:                                              ; preds = %159
  br label %171

171:                                              ; preds = %170
  %172 = load i64, i64* %14, align 8
  %173 = icmp eq i64 %172, 0
  br i1 %173, label %174, label %189

174:                                              ; preds = %171
  %175 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %176 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %175, i32 0, i32 3
  %177 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %176, align 8
  %178 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %179 = call i32 %177(%struct.jpeg_decompress_struct.541* %178)
  %180 = icmp ne i32 %179, 0
  br i1 %180, label %182, label %181

181:                                              ; preds = %174
  store i32 0, i32* %4, align 4
  br label %544

182:                                              ; preds = %174
  %183 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %184 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %183, i32 0, i32 0
  %185 = load i8*, i8** %184, align 8
  store i8* %185, i8** %13, align 8
  %186 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %187 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %186, i32 0, i32 1
  %188 = load i64, i64* %187, align 8
  store i64 %188, i64* %14, align 8
  br label %189

189:                                              ; preds = %182, %171
  %190 = load i64, i64* %14, align 8
  %191 = add i64 %190, -1
  store i64 %191, i64* %14, align 8
  %192 = load i8*, i8** %13, align 8
  %193 = getelementptr inbounds i8, i8* %192, i32 1
  store i8* %193, i8** %13, align 8
  %194 = load i8, i8* %192, align 1
  %195 = zext i8 %194 to i32
  %196 = shl i32 %195, 8
  %197 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %198 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %197, i32 0, i32 6
  store i32 %196, i32* %198, align 8
  %199 = load i64, i64* %14, align 8
  %200 = icmp eq i64 %199, 0
  br i1 %200, label %201, label %216

201:                                              ; preds = %189
  %202 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %203 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %202, i32 0, i32 3
  %204 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %203, align 8
  %205 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %206 = call i32 %204(%struct.jpeg_decompress_struct.541* %205)
  %207 = icmp ne i32 %206, 0
  br i1 %207, label %209, label %208

208:                                              ; preds = %201
  store i32 0, i32* %4, align 4
  br label %544

209:                                              ; preds = %201
  %210 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %211 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %210, i32 0, i32 0
  %212 = load i8*, i8** %211, align 8
  store i8* %212, i8** %13, align 8
  %213 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %214 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %213, i32 0, i32 1
  %215 = load i64, i64* %214, align 8
  store i64 %215, i64* %14, align 8
  br label %216

216:                                              ; preds = %209, %189
  %217 = load i64, i64* %14, align 8
  %218 = add i64 %217, -1
  store i64 %218, i64* %14, align 8
  %219 = load i8*, i8** %13, align 8
  %220 = getelementptr inbounds i8, i8* %219, i32 1
  store i8* %220, i8** %13, align 8
  %221 = load i8, i8* %219, align 1
  %222 = zext i8 %221 to i32
  %223 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %224 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %223, i32 0, i32 6
  %225 = load i32, i32* %224, align 8
  %226 = add i32 %225, %222
  store i32 %226, i32* %224, align 8
  br label %227

227:                                              ; preds = %216
  br label %228

228:                                              ; preds = %227
  %229 = load i64, i64* %14, align 8
  %230 = icmp eq i64 %229, 0
  br i1 %230, label %231, label %246

231:                                              ; preds = %228
  %232 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %233 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %232, i32 0, i32 3
  %234 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %233, align 8
  %235 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %236 = call i32 %234(%struct.jpeg_decompress_struct.541* %235)
  %237 = icmp ne i32 %236, 0
  br i1 %237, label %239, label %238

238:                                              ; preds = %231
  store i32 0, i32* %4, align 4
  br label %544

239:                                              ; preds = %231
  %240 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %241 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %240, i32 0, i32 0
  %242 = load i8*, i8** %241, align 8
  store i8* %242, i8** %13, align 8
  %243 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %244 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %243, i32 0, i32 1
  %245 = load i64, i64* %244, align 8
  store i64 %245, i64* %14, align 8
  br label %246

246:                                              ; preds = %239, %228
  %247 = load i64, i64* %14, align 8
  %248 = add i64 %247, -1
  store i64 %248, i64* %14, align 8
  %249 = load i8*, i8** %13, align 8
  %250 = getelementptr inbounds i8, i8* %249, i32 1
  store i8* %250, i8** %13, align 8
  %251 = load i8, i8* %249, align 1
  %252 = zext i8 %251 to i32
  %253 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %254 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %253, i32 0, i32 8
  store i32 %252, i32* %254, align 8
  br label %255

255:                                              ; preds = %246
  %256 = load i64, i64* %8, align 8
  %257 = sub nsw i64 %256, 8
  store i64 %257, i64* %8, align 8
  br label %258

258:                                              ; preds = %255
  %259 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %260 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %259, i32 0, i32 0
  %261 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %260, align 8
  %262 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %261, i32 0, i32 6
  %263 = bitcast %union.anon* %262 to [8 x i32]*
  %264 = getelementptr inbounds [8 x i32], [8 x i32]* %263, i64 0, i64 0
  store i32* %264, i32** %15, align 8
  %265 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %266 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %265, i32 0, i32 72
  %267 = load i32, i32* %266, align 4
  %268 = load i32*, i32** %15, align 8
  %269 = getelementptr inbounds i32, i32* %268, i64 0
  store i32 %267, i32* %269, align 4
  %270 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %271 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %270, i32 0, i32 6
  %272 = load i32, i32* %271, align 8
  %273 = load i32*, i32** %15, align 8
  %274 = getelementptr inbounds i32, i32* %273, i64 1
  store i32 %272, i32* %274, align 4
  %275 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %276 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %275, i32 0, i32 7
  %277 = load i32, i32* %276, align 4
  %278 = load i32*, i32** %15, align 8
  %279 = getelementptr inbounds i32, i32* %278, i64 2
  store i32 %277, i32* %279, align 4
  %280 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %281 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %280, i32 0, i32 8
  %282 = load i32, i32* %281, align 8
  %283 = load i32*, i32** %15, align 8
  %284 = getelementptr inbounds i32, i32* %283, i64 3
  store i32 %282, i32* %284, align 4
  %285 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %286 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %285, i32 0, i32 0
  %287 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %286, align 8
  %288 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %287, i32 0, i32 5
  store i32 99, i32* %288, align 8
  %289 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %290 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %289, i32 0, i32 0
  %291 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %290, align 8
  %292 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %291, i32 0, i32 1
  %293 = load void (%struct.jpeg_common_struct*, i32)*, void (%struct.jpeg_common_struct*, i32)** %292, align 8
  %294 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %295 = bitcast %struct.jpeg_decompress_struct.541* %294 to %struct.jpeg_common_struct*
  call void %293(%struct.jpeg_common_struct* %295, i32 1)
  br label %296

296:                                              ; preds = %258
  %297 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %298 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %297, i32 0, i32 78
  %299 = load %struct.jpeg_marker_reader.535*, %struct.jpeg_marker_reader.535** %298, align 8
  %300 = getelementptr inbounds %struct.jpeg_marker_reader.535, %struct.jpeg_marker_reader.535* %299, i32 0, i32 6
  %301 = load i32, i32* %300, align 4
  %302 = icmp ne i32 %301, 0
  br i1 %302, label %303, label %315

303:                                              ; preds = %296
  %304 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %305 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %304, i32 0, i32 0
  %306 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %305, align 8
  %307 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %306, i32 0, i32 5
  store i32 57, i32* %307, align 8
  %308 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %309 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %308, i32 0, i32 0
  %310 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %309, align 8
  %311 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %310, i32 0, i32 0
  %312 = load void (%struct.jpeg_common_struct*)*, void (%struct.jpeg_common_struct*)** %311, align 8
  %313 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %314 = bitcast %struct.jpeg_decompress_struct.541* %313 to %struct.jpeg_common_struct*
  call void %312(%struct.jpeg_common_struct* %314)
  br label %315

315:                                              ; preds = %303, %296
  %316 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %317 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %316, i32 0, i32 7
  %318 = load i32, i32* %317, align 4
  %319 = icmp ule i32 %318, 0
  br i1 %319, label %330, label %320

320:                                              ; preds = %315
  %321 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %322 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %321, i32 0, i32 6
  %323 = load i32, i32* %322, align 8
  %324 = icmp ule i32 %323, 0
  br i1 %324, label %330, label %325

325:                                              ; preds = %320
  %326 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %327 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %326, i32 0, i32 8
  %328 = load i32, i32* %327, align 8
  %329 = icmp sle i32 %328, 0
  br i1 %329, label %330, label %342

330:                                              ; preds = %325, %320, %315
  %331 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %332 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %331, i32 0, i32 0
  %333 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %332, align 8
  %334 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %333, i32 0, i32 5
  store i32 31, i32* %334, align 8
  %335 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %336 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %335, i32 0, i32 0
  %337 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %336, align 8
  %338 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %337, i32 0, i32 0
  %339 = load void (%struct.jpeg_common_struct*)*, void (%struct.jpeg_common_struct*)** %338, align 8
  %340 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %341 = bitcast %struct.jpeg_decompress_struct.541* %340 to %struct.jpeg_common_struct*
  call void %339(%struct.jpeg_common_struct* %341)
  br label %342

342:                                              ; preds = %330, %325
  %343 = load i64, i64* %8, align 8
  %344 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %345 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %344, i32 0, i32 8
  %346 = load i32, i32* %345, align 8
  %347 = mul nsw i32 %346, 3
  %348 = sext i32 %347 to i64
  %349 = icmp ne i64 %343, %348
  br i1 %349, label %350, label %362

350:                                              ; preds = %342
  %351 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %352 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %351, i32 0, i32 0
  %353 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %352, align 8
  %354 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %353, i32 0, i32 5
  store i32 9, i32* %354, align 8
  %355 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %356 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %355, i32 0, i32 0
  %357 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %356, align 8
  %358 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %357, i32 0, i32 0
  %359 = load void (%struct.jpeg_common_struct*)*, void (%struct.jpeg_common_struct*)** %358, align 8
  %360 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %361 = bitcast %struct.jpeg_decompress_struct.541* %360 to %struct.jpeg_common_struct*
  call void %359(%struct.jpeg_common_struct* %361)
  br label %362

362:                                              ; preds = %350, %342
  %363 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %364 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %363, i32 0, i32 43
  %365 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %364, align 8
  %366 = icmp eq %struct.jpeg_component_info* %365, null
  br i1 %366, label %367, label %384

367:                                              ; preds = %362
  %368 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %369 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %368, i32 0, i32 1
  %370 = load %struct.jpeg_memory_mgr*, %struct.jpeg_memory_mgr** %369, align 8
  %371 = getelementptr inbounds %struct.jpeg_memory_mgr, %struct.jpeg_memory_mgr* %370, i32 0, i32 0
  %372 = load i8* (%struct.jpeg_common_struct*, i32, i64)*, i8* (%struct.jpeg_common_struct*, i32, i64)** %371, align 8
  %373 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %374 = bitcast %struct.jpeg_decompress_struct.541* %373 to %struct.jpeg_common_struct*
  %375 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %376 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %375, i32 0, i32 8
  %377 = load i32, i32* %376, align 8
  %378 = sext i32 %377 to i64
  %379 = mul i64 %378, 96
  %380 = call i8* %372(%struct.jpeg_common_struct* %374, i32 1, i64 %379)
  %381 = bitcast i8* %380 to %struct.jpeg_component_info*
  %382 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %383 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %382, i32 0, i32 43
  store %struct.jpeg_component_info* %381, %struct.jpeg_component_info** %383, align 8
  br label %384

384:                                              ; preds = %367, %362
  store i32 0, i32* %10, align 4
  %385 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %386 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %385, i32 0, i32 43
  %387 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %386, align 8
  store %struct.jpeg_component_info* %387, %struct.jpeg_component_info** %11, align 8
  br label %388

388:                                              ; preds = %528, %384
  %389 = load i32, i32* %10, align 4
  %390 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %391 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %390, i32 0, i32 8
  %392 = load i32, i32* %391, align 8
  %393 = icmp slt i32 %389, %392
  br i1 %393, label %394, label %533

394:                                              ; preds = %388
  %395 = load i32, i32* %10, align 4
  %396 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %11, align 8
  %397 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %396, i32 0, i32 1
  store i32 %395, i32* %397, align 4
  br label %398

398:                                              ; preds = %394
  %399 = load i64, i64* %14, align 8
  %400 = icmp eq i64 %399, 0
  br i1 %400, label %401, label %416

401:                                              ; preds = %398
  %402 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %403 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %402, i32 0, i32 3
  %404 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %403, align 8
  %405 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %406 = call i32 %404(%struct.jpeg_decompress_struct.541* %405)
  %407 = icmp ne i32 %406, 0
  br i1 %407, label %409, label %408

408:                                              ; preds = %401
  store i32 0, i32* %4, align 4
  br label %544

409:                                              ; preds = %401
  %410 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %411 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %410, i32 0, i32 0
  %412 = load i8*, i8** %411, align 8
  store i8* %412, i8** %13, align 8
  %413 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %414 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %413, i32 0, i32 1
  %415 = load i64, i64* %414, align 8
  store i64 %415, i64* %14, align 8
  br label %416

416:                                              ; preds = %409, %398
  %417 = load i64, i64* %14, align 8
  %418 = add i64 %417, -1
  store i64 %418, i64* %14, align 8
  %419 = load i8*, i8** %13, align 8
  %420 = getelementptr inbounds i8, i8* %419, i32 1
  store i8* %420, i8** %13, align 8
  %421 = load i8, i8* %419, align 1
  %422 = zext i8 %421 to i32
  %423 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %11, align 8
  %424 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %423, i32 0, i32 0
  store i32 %422, i32* %424, align 8
  br label %425

425:                                              ; preds = %416
  br label %426

426:                                              ; preds = %425
  %427 = load i64, i64* %14, align 8
  %428 = icmp eq i64 %427, 0
  br i1 %428, label %429, label %444

429:                                              ; preds = %426
  %430 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %431 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %430, i32 0, i32 3
  %432 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %431, align 8
  %433 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %434 = call i32 %432(%struct.jpeg_decompress_struct.541* %433)
  %435 = icmp ne i32 %434, 0
  br i1 %435, label %437, label %436

436:                                              ; preds = %429
  store i32 0, i32* %4, align 4
  br label %544

437:                                              ; preds = %429
  %438 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %439 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %438, i32 0, i32 0
  %440 = load i8*, i8** %439, align 8
  store i8* %440, i8** %13, align 8
  %441 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %442 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %441, i32 0, i32 1
  %443 = load i64, i64* %442, align 8
  store i64 %443, i64* %14, align 8
  br label %444

444:                                              ; preds = %437, %426
  %445 = load i64, i64* %14, align 8
  %446 = add i64 %445, -1
  store i64 %446, i64* %14, align 8
  %447 = load i8*, i8** %13, align 8
  %448 = getelementptr inbounds i8, i8* %447, i32 1
  store i8* %448, i8** %13, align 8
  %449 = load i8, i8* %447, align 1
  %450 = zext i8 %449 to i32
  store i32 %450, i32* %9, align 4
  br label %451

451:                                              ; preds = %444
  %452 = load i32, i32* %9, align 4
  %453 = ashr i32 %452, 4
  %454 = and i32 %453, 15
  %455 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %11, align 8
  %456 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %455, i32 0, i32 2
  store i32 %454, i32* %456, align 8
  %457 = load i32, i32* %9, align 4
  %458 = and i32 %457, 15
  %459 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %11, align 8
  %460 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %459, i32 0, i32 3
  store i32 %458, i32* %460, align 4
  br label %461

461:                                              ; preds = %451
  %462 = load i64, i64* %14, align 8
  %463 = icmp eq i64 %462, 0
  br i1 %463, label %464, label %479

464:                                              ; preds = %461
  %465 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %466 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %465, i32 0, i32 3
  %467 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %466, align 8
  %468 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %469 = call i32 %467(%struct.jpeg_decompress_struct.541* %468)
  %470 = icmp ne i32 %469, 0
  br i1 %470, label %472, label %471

471:                                              ; preds = %464
  store i32 0, i32* %4, align 4
  br label %544

472:                                              ; preds = %464
  %473 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %474 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %473, i32 0, i32 0
  %475 = load i8*, i8** %474, align 8
  store i8* %475, i8** %13, align 8
  %476 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %477 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %476, i32 0, i32 1
  %478 = load i64, i64* %477, align 8
  store i64 %478, i64* %14, align 8
  br label %479

479:                                              ; preds = %472, %461
  %480 = load i64, i64* %14, align 8
  %481 = add i64 %480, -1
  store i64 %481, i64* %14, align 8
  %482 = load i8*, i8** %13, align 8
  %483 = getelementptr inbounds i8, i8* %482, i32 1
  store i8* %483, i8** %13, align 8
  %484 = load i8, i8* %482, align 1
  %485 = zext i8 %484 to i32
  %486 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %11, align 8
  %487 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %486, i32 0, i32 4
  store i32 %485, i32* %487, align 8
  br label %488

488:                                              ; preds = %479
  br label %489

489:                                              ; preds = %488
  %490 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %491 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %490, i32 0, i32 0
  %492 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %491, align 8
  %493 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %492, i32 0, i32 6
  %494 = bitcast %union.anon* %493 to [8 x i32]*
  %495 = getelementptr inbounds [8 x i32], [8 x i32]* %494, i64 0, i64 0
  store i32* %495, i32** %16, align 8
  %496 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %11, align 8
  %497 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %496, i32 0, i32 0
  %498 = load i32, i32* %497, align 8
  %499 = load i32*, i32** %16, align 8
  %500 = getelementptr inbounds i32, i32* %499, i64 0
  store i32 %498, i32* %500, align 4
  %501 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %11, align 8
  %502 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %501, i32 0, i32 2
  %503 = load i32, i32* %502, align 8
  %504 = load i32*, i32** %16, align 8
  %505 = getelementptr inbounds i32, i32* %504, i64 1
  store i32 %503, i32* %505, align 4
  %506 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %11, align 8
  %507 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %506, i32 0, i32 3
  %508 = load i32, i32* %507, align 4
  %509 = load i32*, i32** %16, align 8
  %510 = getelementptr inbounds i32, i32* %509, i64 2
  store i32 %508, i32* %510, align 4
  %511 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %11, align 8
  %512 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %511, i32 0, i32 4
  %513 = load i32, i32* %512, align 8
  %514 = load i32*, i32** %16, align 8
  %515 = getelementptr inbounds i32, i32* %514, i64 3
  store i32 %513, i32* %515, align 4
  %516 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %517 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %516, i32 0, i32 0
  %518 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %517, align 8
  %519 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %518, i32 0, i32 5
  store i32 100, i32* %519, align 8
  %520 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %521 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %520, i32 0, i32 0
  %522 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %521, align 8
  %523 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %522, i32 0, i32 1
  %524 = load void (%struct.jpeg_common_struct*, i32)*, void (%struct.jpeg_common_struct*, i32)** %523, align 8
  %525 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %526 = bitcast %struct.jpeg_decompress_struct.541* %525 to %struct.jpeg_common_struct*
  call void %524(%struct.jpeg_common_struct* %526, i32 1)
  br label %527

527:                                              ; preds = %489
  br label %528

528:                                              ; preds = %527
  %529 = load i32, i32* %10, align 4
  %530 = add nsw i32 %529, 1
  store i32 %530, i32* %10, align 4
  %531 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %11, align 8
  %532 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %531, i32 1
  store %struct.jpeg_component_info* %532, %struct.jpeg_component_info** %11, align 8
  br label %388, !llvm.loop !7

533:                                              ; preds = %388
  %534 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %5, align 8
  %535 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %534, i32 0, i32 78
  %536 = load %struct.jpeg_marker_reader.535*, %struct.jpeg_marker_reader.535** %535, align 8
  %537 = getelementptr inbounds %struct.jpeg_marker_reader.535, %struct.jpeg_marker_reader.535* %536, i32 0, i32 6
  store i32 1, i32* %537, align 4
  %538 = load i8*, i8** %13, align 8
  %539 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %540 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %539, i32 0, i32 0
  store i8* %538, i8** %540, align 8
  %541 = load i64, i64* %14, align 8
  %542 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %12, align 8
  %543 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %542, i32 0, i32 1
  store i64 %541, i64* %543, align 8
  store i32 1, i32* %4, align 4
  br label %544

544:                                              ; preds = %533, %471, %436, %408, %238, %208, %181, %151, %124, %96, %68, %42
  %545 = load i32, i32* %4, align 4
  ret i32 %545
}

; Function Attrs: noinline nounwind optnone ssp uwtable
define hidden i32 @get_sos(%struct.jpeg_decompress_struct.541* %0) #0 {
  %2 = alloca i32, align 4
  %3 = alloca %struct.jpeg_decompress_struct.541*, align 8
  %4 = alloca i64, align 8
  %5 = alloca i32, align 4
  %6 = alloca i32, align 4
  %7 = alloca i32, align 4
  %8 = alloca i32, align 4
  %9 = alloca i32, align 4
  %10 = alloca %struct.jpeg_component_info*, align 8
  %11 = alloca %struct.jpeg_source_mgr.526*, align 8
  %12 = alloca i8*, align 8
  %13 = alloca i64, align 8
  %14 = alloca i32*, align 8
  %15 = alloca i32*, align 8
  store %struct.jpeg_decompress_struct.541* %0, %struct.jpeg_decompress_struct.541** %3, align 8
  %16 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %17 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %16, i32 0, i32 5
  %18 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %17, align 8
  store %struct.jpeg_source_mgr.526* %18, %struct.jpeg_source_mgr.526** %11, align 8
  %19 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %20 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %19, i32 0, i32 0
  %21 = load i8*, i8** %20, align 8
  store i8* %21, i8** %12, align 8
  %22 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %23 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %22, i32 0, i32 1
  %24 = load i64, i64* %23, align 8
  store i64 %24, i64* %13, align 8
  %25 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %26 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %25, i32 0, i32 78
  %27 = load %struct.jpeg_marker_reader.535*, %struct.jpeg_marker_reader.535** %26, align 8
  %28 = getelementptr inbounds %struct.jpeg_marker_reader.535, %struct.jpeg_marker_reader.535* %27, i32 0, i32 6
  %29 = load i32, i32* %28, align 4
  %30 = icmp ne i32 %29, 0
  br i1 %30, label %43, label %31

31:                                               ; preds = %1
  %32 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %33 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %32, i32 0, i32 0
  %34 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %33, align 8
  %35 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %34, i32 0, i32 5
  store i32 61, i32* %35, align 8
  %36 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %37 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %36, i32 0, i32 0
  %38 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %37, align 8
  %39 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %38, i32 0, i32 0
  %40 = load void (%struct.jpeg_common_struct*)*, void (%struct.jpeg_common_struct*)** %39, align 8
  %41 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %42 = bitcast %struct.jpeg_decompress_struct.541* %41 to %struct.jpeg_common_struct*
  call void %40(%struct.jpeg_common_struct* %42)
  br label %43

43:                                               ; preds = %31, %1
  br label %44

44:                                               ; preds = %43
  %45 = load i64, i64* %13, align 8
  %46 = icmp eq i64 %45, 0
  br i1 %46, label %47, label %62

47:                                               ; preds = %44
  %48 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %49 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %48, i32 0, i32 3
  %50 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %49, align 8
  %51 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %52 = call i32 %50(%struct.jpeg_decompress_struct.541* %51)
  %53 = icmp ne i32 %52, 0
  br i1 %53, label %55, label %54

54:                                               ; preds = %47
  store i32 0, i32* %2, align 4
  br label %466

55:                                               ; preds = %47
  %56 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %57 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %56, i32 0, i32 0
  %58 = load i8*, i8** %57, align 8
  store i8* %58, i8** %12, align 8
  %59 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %60 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %59, i32 0, i32 1
  %61 = load i64, i64* %60, align 8
  store i64 %61, i64* %13, align 8
  br label %62

62:                                               ; preds = %55, %44
  %63 = load i64, i64* %13, align 8
  %64 = add i64 %63, -1
  store i64 %64, i64* %13, align 8
  %65 = load i8*, i8** %12, align 8
  %66 = getelementptr inbounds i8, i8* %65, i32 1
  store i8* %66, i8** %12, align 8
  %67 = load i8, i8* %65, align 1
  %68 = zext i8 %67 to i32
  %69 = shl i32 %68, 8
  %70 = zext i32 %69 to i64
  store i64 %70, i64* %4, align 8
  %71 = load i64, i64* %13, align 8
  %72 = icmp eq i64 %71, 0
  br i1 %72, label %73, label %88

73:                                               ; preds = %62
  %74 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %75 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %74, i32 0, i32 3
  %76 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %75, align 8
  %77 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %78 = call i32 %76(%struct.jpeg_decompress_struct.541* %77)
  %79 = icmp ne i32 %78, 0
  br i1 %79, label %81, label %80

80:                                               ; preds = %73
  store i32 0, i32* %2, align 4
  br label %466

81:                                               ; preds = %73
  %82 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %83 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %82, i32 0, i32 0
  %84 = load i8*, i8** %83, align 8
  store i8* %84, i8** %12, align 8
  %85 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %86 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %85, i32 0, i32 1
  %87 = load i64, i64* %86, align 8
  store i64 %87, i64* %13, align 8
  br label %88

88:                                               ; preds = %81, %62
  %89 = load i64, i64* %13, align 8
  %90 = add i64 %89, -1
  store i64 %90, i64* %13, align 8
  %91 = load i8*, i8** %12, align 8
  %92 = getelementptr inbounds i8, i8* %91, i32 1
  store i8* %92, i8** %12, align 8
  %93 = load i8, i8* %91, align 1
  %94 = zext i8 %93 to i64
  %95 = load i64, i64* %4, align 8
  %96 = add nsw i64 %95, %94
  store i64 %96, i64* %4, align 8
  br label %97

97:                                               ; preds = %88
  br label %98

98:                                               ; preds = %97
  %99 = load i64, i64* %13, align 8
  %100 = icmp eq i64 %99, 0
  br i1 %100, label %101, label %116

101:                                              ; preds = %98
  %102 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %103 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %102, i32 0, i32 3
  %104 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %103, align 8
  %105 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %106 = call i32 %104(%struct.jpeg_decompress_struct.541* %105)
  %107 = icmp ne i32 %106, 0
  br i1 %107, label %109, label %108

108:                                              ; preds = %101
  store i32 0, i32* %2, align 4
  br label %466

109:                                              ; preds = %101
  %110 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %111 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %110, i32 0, i32 0
  %112 = load i8*, i8** %111, align 8
  store i8* %112, i8** %12, align 8
  %113 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %114 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %113, i32 0, i32 1
  %115 = load i64, i64* %114, align 8
  store i64 %115, i64* %13, align 8
  br label %116

116:                                              ; preds = %109, %98
  %117 = load i64, i64* %13, align 8
  %118 = add i64 %117, -1
  store i64 %118, i64* %13, align 8
  %119 = load i8*, i8** %12, align 8
  %120 = getelementptr inbounds i8, i8* %119, i32 1
  store i8* %120, i8** %12, align 8
  %121 = load i8, i8* %119, align 1
  %122 = zext i8 %121 to i32
  store i32 %122, i32* %7, align 4
  br label %123

123:                                              ; preds = %116
  %124 = load i64, i64* %4, align 8
  %125 = load i32, i32* %7, align 4
  %126 = mul nsw i32 %125, 2
  %127 = add nsw i32 %126, 6
  %128 = sext i32 %127 to i64
  %129 = icmp ne i64 %124, %128
  br i1 %129, label %136, label %130

130:                                              ; preds = %123
  %131 = load i32, i32* %7, align 4
  %132 = icmp slt i32 %131, 1
  br i1 %132, label %136, label %133

133:                                              ; preds = %130
  %134 = load i32, i32* %7, align 4
  %135 = icmp sgt i32 %134, 4
  br i1 %135, label %136, label %148

136:                                              ; preds = %133, %130, %123
  %137 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %138 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %137, i32 0, i32 0
  %139 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %138, align 8
  %140 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %139, i32 0, i32 5
  store i32 9, i32* %140, align 8
  %141 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %142 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %141, i32 0, i32 0
  %143 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %142, align 8
  %144 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %143, i32 0, i32 0
  %145 = load void (%struct.jpeg_common_struct*)*, void (%struct.jpeg_common_struct*)** %144, align 8
  %146 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %147 = bitcast %struct.jpeg_decompress_struct.541* %146 to %struct.jpeg_common_struct*
  call void %145(%struct.jpeg_common_struct* %147)
  br label %148

148:                                              ; preds = %136, %133
  %149 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %150 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %149, i32 0, i32 0
  %151 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %150, align 8
  %152 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %151, i32 0, i32 5
  store i32 102, i32* %152, align 8
  %153 = load i32, i32* %7, align 4
  %154 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %155 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %154, i32 0, i32 0
  %156 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %155, align 8
  %157 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %156, i32 0, i32 6
  %158 = bitcast %union.anon* %157 to [8 x i32]*
  %159 = getelementptr inbounds [8 x i32], [8 x i32]* %158, i64 0, i64 0
  store i32 %153, i32* %159, align 4
  %160 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %161 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %160, i32 0, i32 0
  %162 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %161, align 8
  %163 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %162, i32 0, i32 1
  %164 = load void (%struct.jpeg_common_struct*, i32)*, void (%struct.jpeg_common_struct*, i32)** %163, align 8
  %165 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %166 = bitcast %struct.jpeg_decompress_struct.541* %165 to %struct.jpeg_common_struct*
  call void %164(%struct.jpeg_common_struct* %166, i32 1)
  %167 = load i32, i32* %7, align 4
  %168 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %169 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %168, i32 0, i32 62
  store i32 %167, i32* %169, align 8
  store i32 0, i32* %5, align 4
  br label %170

170:                                              ; preds = %316, %148
  %171 = load i32, i32* %5, align 4
  %172 = load i32, i32* %7, align 4
  %173 = icmp slt i32 %171, %172
  br i1 %173, label %174, label %319

174:                                              ; preds = %170
  br label %175

175:                                              ; preds = %174
  %176 = load i64, i64* %13, align 8
  %177 = icmp eq i64 %176, 0
  br i1 %177, label %178, label %193

178:                                              ; preds = %175
  %179 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %180 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %179, i32 0, i32 3
  %181 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %180, align 8
  %182 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %183 = call i32 %181(%struct.jpeg_decompress_struct.541* %182)
  %184 = icmp ne i32 %183, 0
  br i1 %184, label %186, label %185

185:                                              ; preds = %178
  store i32 0, i32* %2, align 4
  br label %466

186:                                              ; preds = %178
  %187 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %188 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %187, i32 0, i32 0
  %189 = load i8*, i8** %188, align 8
  store i8* %189, i8** %12, align 8
  %190 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %191 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %190, i32 0, i32 1
  %192 = load i64, i64* %191, align 8
  store i64 %192, i64* %13, align 8
  br label %193

193:                                              ; preds = %186, %175
  %194 = load i64, i64* %13, align 8
  %195 = add i64 %194, -1
  store i64 %195, i64* %13, align 8
  %196 = load i8*, i8** %12, align 8
  %197 = getelementptr inbounds i8, i8* %196, i32 1
  store i8* %197, i8** %12, align 8
  %198 = load i8, i8* %196, align 1
  %199 = zext i8 %198 to i32
  store i32 %199, i32* %9, align 4
  br label %200

200:                                              ; preds = %193
  br label %201

201:                                              ; preds = %200
  %202 = load i64, i64* %13, align 8
  %203 = icmp eq i64 %202, 0
  br i1 %203, label %204, label %219

204:                                              ; preds = %201
  %205 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %206 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %205, i32 0, i32 3
  %207 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %206, align 8
  %208 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %209 = call i32 %207(%struct.jpeg_decompress_struct.541* %208)
  %210 = icmp ne i32 %209, 0
  br i1 %210, label %212, label %211

211:                                              ; preds = %204
  store i32 0, i32* %2, align 4
  br label %466

212:                                              ; preds = %204
  %213 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %214 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %213, i32 0, i32 0
  %215 = load i8*, i8** %214, align 8
  store i8* %215, i8** %12, align 8
  %216 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %217 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %216, i32 0, i32 1
  %218 = load i64, i64* %217, align 8
  store i64 %218, i64* %13, align 8
  br label %219

219:                                              ; preds = %212, %201
  %220 = load i64, i64* %13, align 8
  %221 = add i64 %220, -1
  store i64 %221, i64* %13, align 8
  %222 = load i8*, i8** %12, align 8
  %223 = getelementptr inbounds i8, i8* %222, i32 1
  store i8* %223, i8** %12, align 8
  %224 = load i8, i8* %222, align 1
  %225 = zext i8 %224 to i32
  store i32 %225, i32* %8, align 4
  br label %226

226:                                              ; preds = %219
  store i32 0, i32* %6, align 4
  %227 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %228 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %227, i32 0, i32 43
  %229 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %228, align 8
  store %struct.jpeg_component_info* %229, %struct.jpeg_component_info** %10, align 8
  br label %230

230:                                              ; preds = %244, %226
  %231 = load i32, i32* %6, align 4
  %232 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %233 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %232, i32 0, i32 8
  %234 = load i32, i32* %233, align 8
  %235 = icmp slt i32 %231, %234
  br i1 %235, label %236, label %249

236:                                              ; preds = %230
  %237 = load i32, i32* %9, align 4
  %238 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %10, align 8
  %239 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %238, i32 0, i32 0
  %240 = load i32, i32* %239, align 8
  %241 = icmp eq i32 %237, %240
  br i1 %241, label %242, label %243

242:                                              ; preds = %236
  br label %268

243:                                              ; preds = %236
  br label %244

244:                                              ; preds = %243
  %245 = load i32, i32* %6, align 4
  %246 = add nsw i32 %245, 1
  store i32 %246, i32* %6, align 4
  %247 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %10, align 8
  %248 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %247, i32 1
  store %struct.jpeg_component_info* %248, %struct.jpeg_component_info** %10, align 8
  br label %230, !llvm.loop !9

249:                                              ; preds = %230
  %250 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %251 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %250, i32 0, i32 0
  %252 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %251, align 8
  %253 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %252, i32 0, i32 5
  store i32 5, i32* %253, align 8
  %254 = load i32, i32* %9, align 4
  %255 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %256 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %255, i32 0, i32 0
  %257 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %256, align 8
  %258 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %257, i32 0, i32 6
  %259 = bitcast %union.anon* %258 to [8 x i32]*
  %260 = getelementptr inbounds [8 x i32], [8 x i32]* %259, i64 0, i64 0
  store i32 %254, i32* %260, align 4
  %261 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %262 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %261, i32 0, i32 0
  %263 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %262, align 8
  %264 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %263, i32 0, i32 0
  %265 = load void (%struct.jpeg_common_struct*)*, void (%struct.jpeg_common_struct*)** %264, align 8
  %266 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %267 = bitcast %struct.jpeg_decompress_struct.541* %266 to %struct.jpeg_common_struct*
  call void %265(%struct.jpeg_common_struct* %267)
  br label %268

268:                                              ; preds = %249, %242
  %269 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %10, align 8
  %270 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %271 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %270, i32 0, i32 63
  %272 = load i32, i32* %5, align 4
  %273 = sext i32 %272 to i64
  %274 = getelementptr inbounds [4 x %struct.jpeg_component_info*], [4 x %struct.jpeg_component_info*]* %271, i64 0, i64 %273
  store %struct.jpeg_component_info* %269, %struct.jpeg_component_info** %274, align 8
  %275 = load i32, i32* %8, align 4
  %276 = ashr i32 %275, 4
  %277 = and i32 %276, 15
  %278 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %10, align 8
  %279 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %278, i32 0, i32 5
  store i32 %277, i32* %279, align 4
  %280 = load i32, i32* %8, align 4
  %281 = and i32 %280, 15
  %282 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %10, align 8
  %283 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %282, i32 0, i32 6
  store i32 %281, i32* %283, align 8
  br label %284

284:                                              ; preds = %268
  %285 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %286 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %285, i32 0, i32 0
  %287 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %286, align 8
  %288 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %287, i32 0, i32 6
  %289 = bitcast %union.anon* %288 to [8 x i32]*
  %290 = getelementptr inbounds [8 x i32], [8 x i32]* %289, i64 0, i64 0
  store i32* %290, i32** %14, align 8
  %291 = load i32, i32* %9, align 4
  %292 = load i32*, i32** %14, align 8
  %293 = getelementptr inbounds i32, i32* %292, i64 0
  store i32 %291, i32* %293, align 4
  %294 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %10, align 8
  %295 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %294, i32 0, i32 5
  %296 = load i32, i32* %295, align 4
  %297 = load i32*, i32** %14, align 8
  %298 = getelementptr inbounds i32, i32* %297, i64 1
  store i32 %296, i32* %298, align 4
  %299 = load %struct.jpeg_component_info*, %struct.jpeg_component_info** %10, align 8
  %300 = getelementptr inbounds %struct.jpeg_component_info, %struct.jpeg_component_info* %299, i32 0, i32 6
  %301 = load i32, i32* %300, align 8
  %302 = load i32*, i32** %14, align 8
  %303 = getelementptr inbounds i32, i32* %302, i64 2
  store i32 %301, i32* %303, align 4
  %304 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %305 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %304, i32 0, i32 0
  %306 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %305, align 8
  %307 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %306, i32 0, i32 5
  store i32 103, i32* %307, align 8
  %308 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %309 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %308, i32 0, i32 0
  %310 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %309, align 8
  %311 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %310, i32 0, i32 1
  %312 = load void (%struct.jpeg_common_struct*, i32)*, void (%struct.jpeg_common_struct*, i32)** %311, align 8
  %313 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %314 = bitcast %struct.jpeg_decompress_struct.541* %313 to %struct.jpeg_common_struct*
  call void %312(%struct.jpeg_common_struct* %314, i32 1)
  br label %315

315:                                              ; preds = %284
  br label %316

316:                                              ; preds = %315
  %317 = load i32, i32* %5, align 4
  %318 = add nsw i32 %317, 1
  store i32 %318, i32* %5, align 4
  br label %170, !llvm.loop !10

319:                                              ; preds = %170
  br label %320

320:                                              ; preds = %319
  %321 = load i64, i64* %13, align 8
  %322 = icmp eq i64 %321, 0
  br i1 %322, label %323, label %338

323:                                              ; preds = %320
  %324 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %325 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %324, i32 0, i32 3
  %326 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %325, align 8
  %327 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %328 = call i32 %326(%struct.jpeg_decompress_struct.541* %327)
  %329 = icmp ne i32 %328, 0
  br i1 %329, label %331, label %330

330:                                              ; preds = %323
  store i32 0, i32* %2, align 4
  br label %466

331:                                              ; preds = %323
  %332 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %333 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %332, i32 0, i32 0
  %334 = load i8*, i8** %333, align 8
  store i8* %334, i8** %12, align 8
  %335 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %336 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %335, i32 0, i32 1
  %337 = load i64, i64* %336, align 8
  store i64 %337, i64* %13, align 8
  br label %338

338:                                              ; preds = %331, %320
  %339 = load i64, i64* %13, align 8
  %340 = add i64 %339, -1
  store i64 %340, i64* %13, align 8
  %341 = load i8*, i8** %12, align 8
  %342 = getelementptr inbounds i8, i8* %341, i32 1
  store i8* %342, i8** %12, align 8
  %343 = load i8, i8* %341, align 1
  %344 = zext i8 %343 to i32
  store i32 %344, i32* %8, align 4
  br label %345

345:                                              ; preds = %338
  %346 = load i32, i32* %8, align 4
  %347 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %348 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %347, i32 0, i32 68
  store i32 %346, i32* %348, align 4
  br label %349

349:                                              ; preds = %345
  %350 = load i64, i64* %13, align 8
  %351 = icmp eq i64 %350, 0
  br i1 %351, label %352, label %367

352:                                              ; preds = %349
  %353 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %354 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %353, i32 0, i32 3
  %355 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %354, align 8
  %356 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %357 = call i32 %355(%struct.jpeg_decompress_struct.541* %356)
  %358 = icmp ne i32 %357, 0
  br i1 %358, label %360, label %359

359:                                              ; preds = %352
  store i32 0, i32* %2, align 4
  br label %466

360:                                              ; preds = %352
  %361 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %362 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %361, i32 0, i32 0
  %363 = load i8*, i8** %362, align 8
  store i8* %363, i8** %12, align 8
  %364 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %365 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %364, i32 0, i32 1
  %366 = load i64, i64* %365, align 8
  store i64 %366, i64* %13, align 8
  br label %367

367:                                              ; preds = %360, %349
  %368 = load i64, i64* %13, align 8
  %369 = add i64 %368, -1
  store i64 %369, i64* %13, align 8
  %370 = load i8*, i8** %12, align 8
  %371 = getelementptr inbounds i8, i8* %370, i32 1
  store i8* %371, i8** %12, align 8
  %372 = load i8, i8* %370, align 1
  %373 = zext i8 %372 to i32
  store i32 %373, i32* %8, align 4
  br label %374

374:                                              ; preds = %367
  %375 = load i32, i32* %8, align 4
  %376 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %377 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %376, i32 0, i32 69
  store i32 %375, i32* %377, align 8
  br label %378

378:                                              ; preds = %374
  %379 = load i64, i64* %13, align 8
  %380 = icmp eq i64 %379, 0
  br i1 %380, label %381, label %396

381:                                              ; preds = %378
  %382 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %383 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %382, i32 0, i32 3
  %384 = load i32 (%struct.jpeg_decompress_struct.541*)*, i32 (%struct.jpeg_decompress_struct.541*)** %383, align 8
  %385 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %386 = call i32 %384(%struct.jpeg_decompress_struct.541* %385)
  %387 = icmp ne i32 %386, 0
  br i1 %387, label %389, label %388

388:                                              ; preds = %381
  store i32 0, i32* %2, align 4
  br label %466

389:                                              ; preds = %381
  %390 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %391 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %390, i32 0, i32 0
  %392 = load i8*, i8** %391, align 8
  store i8* %392, i8** %12, align 8
  %393 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %394 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %393, i32 0, i32 1
  %395 = load i64, i64* %394, align 8
  store i64 %395, i64* %13, align 8
  br label %396

396:                                              ; preds = %389, %378
  %397 = load i64, i64* %13, align 8
  %398 = add i64 %397, -1
  store i64 %398, i64* %13, align 8
  %399 = load i8*, i8** %12, align 8
  %400 = getelementptr inbounds i8, i8* %399, i32 1
  store i8* %400, i8** %12, align 8
  %401 = load i8, i8* %399, align 1
  %402 = zext i8 %401 to i32
  store i32 %402, i32* %8, align 4
  br label %403

403:                                              ; preds = %396
  %404 = load i32, i32* %8, align 4
  %405 = ashr i32 %404, 4
  %406 = and i32 %405, 15
  %407 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %408 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %407, i32 0, i32 70
  store i32 %406, i32* %408, align 4
  %409 = load i32, i32* %8, align 4
  %410 = and i32 %409, 15
  %411 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %412 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %411, i32 0, i32 71
  store i32 %410, i32* %412, align 8
  br label %413

413:                                              ; preds = %403
  %414 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %415 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %414, i32 0, i32 0
  %416 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %415, align 8
  %417 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %416, i32 0, i32 6
  %418 = bitcast %union.anon* %417 to [8 x i32]*
  %419 = getelementptr inbounds [8 x i32], [8 x i32]* %418, i64 0, i64 0
  store i32* %419, i32** %15, align 8
  %420 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %421 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %420, i32 0, i32 68
  %422 = load i32, i32* %421, align 4
  %423 = load i32*, i32** %15, align 8
  %424 = getelementptr inbounds i32, i32* %423, i64 0
  store i32 %422, i32* %424, align 4
  %425 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %426 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %425, i32 0, i32 69
  %427 = load i32, i32* %426, align 8
  %428 = load i32*, i32** %15, align 8
  %429 = getelementptr inbounds i32, i32* %428, i64 1
  store i32 %427, i32* %429, align 4
  %430 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %431 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %430, i32 0, i32 70
  %432 = load i32, i32* %431, align 4
  %433 = load i32*, i32** %15, align 8
  %434 = getelementptr inbounds i32, i32* %433, i64 2
  store i32 %432, i32* %434, align 4
  %435 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %436 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %435, i32 0, i32 71
  %437 = load i32, i32* %436, align 8
  %438 = load i32*, i32** %15, align 8
  %439 = getelementptr inbounds i32, i32* %438, i64 3
  store i32 %437, i32* %439, align 4
  %440 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %441 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %440, i32 0, i32 0
  %442 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %441, align 8
  %443 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %442, i32 0, i32 5
  store i32 104, i32* %443, align 8
  %444 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %445 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %444, i32 0, i32 0
  %446 = load %struct.jpeg_error_mgr*, %struct.jpeg_error_mgr** %445, align 8
  %447 = getelementptr inbounds %struct.jpeg_error_mgr, %struct.jpeg_error_mgr* %446, i32 0, i32 1
  %448 = load void (%struct.jpeg_common_struct*, i32)*, void (%struct.jpeg_common_struct*, i32)** %447, align 8
  %449 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %450 = bitcast %struct.jpeg_decompress_struct.541* %449 to %struct.jpeg_common_struct*
  call void %448(%struct.jpeg_common_struct* %450, i32 1)
  br label %451

451:                                              ; preds = %413
  %452 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %453 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %452, i32 0, i32 78
  %454 = load %struct.jpeg_marker_reader.535*, %struct.jpeg_marker_reader.535** %453, align 8
  %455 = getelementptr inbounds %struct.jpeg_marker_reader.535, %struct.jpeg_marker_reader.535* %454, i32 0, i32 7
  store i32 0, i32* %455, align 8
  %456 = load %struct.jpeg_decompress_struct.541*, %struct.jpeg_decompress_struct.541** %3, align 8
  %457 = getelementptr inbounds %struct.jpeg_decompress_struct.541, %struct.jpeg_decompress_struct.541* %456, i32 0, i32 34
  %458 = load i32, i32* %457, align 4
  %459 = add nsw i32 %458, 1
  store i32 %459, i32* %457, align 4
  %460 = load i8*, i8** %12, align 8
  %461 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %462 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %461, i32 0, i32 0
  store i8* %460, i8** %462, align 8
  %463 = load i64, i64* %13, align 8
  %464 = load %struct.jpeg_source_mgr.526*, %struct.jpeg_source_mgr.526** %11, align 8
  %465 = getelementptr inbounds %struct.jpeg_source_mgr.526, %struct.jpeg_source_mgr.526* %464, i32 0, i32 1
  store i64 %463, i64* %465, align 8
  store i32 1, i32* %2, align 4
  br label %466

466:                                              ; preds = %451, %388, %359, %330, %211, %185, %108, %80, %54
  %467 = load i32, i32* %2, align 4
  ret i32 %467
}

attributes #0 = { noinline nounwind optnone ssp uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }

!llvm.ident = !{!0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0, !0}
!llvm.module.flags = !{!1, !2, !3, !4, !5, !6}

!0 = !{!"clang version 13.0.0 (https://github.com/llvm/llvm-project/ 24c8eaec9467b2aaf70b0db33a4e4dd415139a50)"}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 7, !"PIC Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 1}
!4 = !{i32 7, !"frame-pointer", i32 2}
!5 = !{i32 1, !"ThinLTO", i32 0}
!6 = !{i32 1, !"EnableSplitLTOUnit", i32 1}
!7 = distinct !{!7, !8}
!8 = !{!"llvm.loop.mustprogress"}
!9 = distinct !{!9, !8}
!10 = distinct !{!10, !8}
