name: Tests
on: [push]
env:
  LLVM_SIZE_BENCHMARK_SUITE_VERSION: c0a4ee7eded3e9d95a3c440d735456b1f92cb1ed
jobs:
  build-plugin:
    strategy:
      fail-fast: true
      matrix:
        # TODO: Enable after LLVM 14 support
        llvm-version: [13]
        os: [ubuntu-20.04]
    name: Build plugin library with LLVM ${{ matrix.llvm-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y ninja-build
    - uses: ./.github/actions/install-llvm-toolchain
      with:
        version: ${{ matrix.llvm-version }}
        os: ${{ matrix.os }}
    - run: cmake -B build -G Ninja -DLLVM_DIR:PATH="$LLVM_ROOT/lib/cmake/llvm" -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo
    - run: cmake --build ./build
    - run: DESTDIR=./install cmake --install ./build
    - uses: actions/upload-artifact@v3
      with:
        name: LLVMNextFM-${{ matrix.llvm-version }}-${{ matrix.os }}
        path: ./install

  build-and-test:
    strategy:
      fail-fast: true
      matrix:
        # TODO: Enable after LLVM 14 support
        llvm-version: [13]
        os: [ubuntu-20.04]
    name: Build and Test with LLVM ${{ matrix.llvm-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y ninja-build
    - run: sudo pip3 install lit
    - uses: ./.github/actions/install-llvm-toolchain
      with:
        version: ${{ matrix.llvm-version }}
        os: ${{ matrix.os }}
    - run: cmake -B build -G Ninja -DBUILD_TESTING:BOOL=ON -DLLVM_DIR:PATH="$LLVM_ROOT/lib/cmake/llvm"
    - run: cmake --build ./build
    - run: cmake --build ./build --target check

  build-benchmark-suite:
    name: Build Benchmark Suite
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        repository: kateinoigakukun/llvm-size-benchmark-suite
        ref: ${{ env.LLVM_SIZE_BENCHMARK_SUITE_VERSION }}
    - uses: bazelbuild/setup-bazelisk@v2
    - uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel-v1
    # FIXME: Need to install tools required for building Linux build tools
    - run: sudo apt-get install -y libelf-dev llvm clang lld
    - run: bazel build //:bitcode_tar --verbose_failures --subcommands
    # WORKAROUND: Copy out from symlinked directory to avoid upload-artifact issue
    # https://github.com/actions/upload-artifact/issues/92
    - run: cp bazel-bin/bitcode_tar.tar bitcode_tar.tar
    - uses: actions/upload-artifact@v3
      with:
        name: benchmark-suite-tarball
        path: bitcode_tar.tar

  run-benchmark-suite:
    strategy:
      fail-fast: true
      matrix:
        driver-options:
        - name: Multiple Function Merging (limiting 4 functions)
          args: "'-Xopt=--passes=multiple-func-merging,default<Oz>' '-Xopt=--func-merging-explore=3'"
        - name: Multiple Function Merging (limiting 3 functions)
          args: "'-Xopt=--passes=multiple-func-merging,default<Oz>' '-Xopt=--func-merging-explore=2'"
        - name: Function Merging (2 functions)
          args: "'-Xopt=--passes=func-merging,default<Oz>'"
        # TODO: Enable after LLVM 14 support
        llvm-version: [13]
        os: [ubuntu-20.04]
    needs: [build-plugin, build-benchmark-suite]
    name: Run Benchmark Suite (${{ matrix.driver-options.name }})
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-llvm-toolchain
      with:
        version: ${{ matrix.llvm-version }}
        os: ${{ matrix.os }}
    - uses: actions/checkout@v3
      with:
        repository: kateinoigakukun/llvm-size-benchmark-suite
        ref: ${{ env.LLVM_SIZE_BENCHMARK_SUITE_VERSION }}
    - uses: actions/download-artifact@v3
      with:
        name: benchmark-suite-tarball
        path: ./artifacts
    - uses: actions/download-artifact@v3
      with:
        name: LLVMNextFM-${{ matrix.llvm-version }}-${{ matrix.os }}
        path: ./artifacts
    - run: tar xf artifacts/bitcode_tar.tar -C ./artifacts
    - run: |
        echo "## ${{ matrix.driver-options.name }}" >> $GITHUB_STEP_SUMMARY
        ./utils/bmark_driver/main.py \
          --llctool=$LLVM_ROOT/bin/llc \
          --opttool=$LLVM_ROOT/bin/opt \
          --ldtool=$LLVM_ROOT/bin/clang \
          --pass-plugin="artifacts/usr/local/lib/LLVMNextFM.so" \
          --suite-path ./artifacts/benchmarks/mibench \
          --paralell --reporter markdown \
          ${{ matrix.driver-options.args }} >> $GITHUB_STEP_SUMMARY
