name: Tests
on: [push]
jobs:
  build-and-test:
    strategy:
      fail-fast: true
      matrix:
        include:
        - llvm-version: 13
          llvm-apt-source: "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main"
          llvm-packages: llvm-13 llvm-13-dev llvm-13-tools clang-13
          llvm-dir: /usr/lib/llvm-13
          build-os: ubuntu-20.04
      # TODO: Enable after LLVM 14 support
      # - llvm-version: 14
      #   llvm-apt-source: "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main"
      #   llvm-packages: llvm-14 llvm-14-dev llvm-14-tools clang-14
      #   llvm-dir: /usr/lib/llvm-14
      #   build-os: ubuntu-20.04
    name: Build and Test with LLVM ${{ matrix.llvm-version }} (${{ matrix.build-os }})
    runs-on: ${{ matrix.build-os }}
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y ninja-build
    - run: sudo pip3 install lit
    - name: Install LLVM ${{ matrix.llvm-version }}
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-add-repository "${{ matrix.llvm-apt-source }}"
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.llvm-packages }}
        echo "${{ matrix.llvm-dir }}/bin" >> $GITHUB_PATH

    - run: cmake -B build -G Ninja -DBUILD_TESTING:BOOL=ON -DLLVM_DIR:PATH="${{ matrix.llvm-dir }}/lib/cmake/llvm"
    - run: cmake --build ./build
    - run: lit ./build/test -v
  
